"""initial_schema_with_all_tables

Revision ID: 4f1bc033c9cb
Revises: 
Create Date: 2025-10-18 13:21:56.109582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f1bc033c9cb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('required_skills', sa.JSON(), nullable=True),
    sa.Column('preferred_skills', sa.JSON(), nullable=True),
    sa.Column('min_experience_years', sa.Integer(), nullable=True),
    sa.Column('max_experience_years', sa.Integer(), nullable=True),
    sa.Column('education_requirements', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('salary_range', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', 'DRAFT', name='jobstatusenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_title'), 'jobs', ['title'], unique=False)
    op.create_table('model_metadata',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('s3_path', sa.String(length=500), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('training_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_metadata_is_active'), 'model_metadata', ['is_active'], unique=False)
    op.create_index(op.f('ix_model_metadata_version'), 'model_metadata', ['version'], unique=True)
    op.create_table('resumes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidate_name', sa.String(length=200), nullable=True),
    sa.Column('candidate_email', sa.String(length=200), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('experience_years', sa.Float(), nullable=True),
    sa.Column('education', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_candidate_email'), 'resumes', ['candidate_email'], unique=False)
    op.create_index(op.f('ix_resumes_candidate_name'), 'resumes', ['candidate_name'], unique=False)
    op.create_index(op.f('ix_resumes_created_at'), 'resumes', ['created_at'], unique=False)
    op.create_table('screening_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('resume_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='screeningstatusenum'), nullable=False),
    sa.Column('decision', sa.Enum('SHORTLIST', 'REJECT', 'REVIEW', name='screeningdecisionenum'), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('similarity_overall_score', sa.Float(), nullable=True),
    sa.Column('similarity_skills_match', sa.Float(), nullable=True),
    sa.Column('similarity_experience_match', sa.Float(), nullable=True),
    sa.Column('similarity_education_match', sa.Float(), nullable=True),
    sa.Column('similarity_semantic', sa.Float(), nullable=True),
    sa.Column('classifier_probability', sa.Float(), nullable=True),
    sa.Column('classifier_confidence', sa.Float(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('matched_skills', sa.JSON(), nullable=True),
    sa.Column('missing_skills', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screening_results_created_at'), 'screening_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_screening_results_decision'), 'screening_results', ['decision'], unique=False)
    op.create_index(op.f('ix_screening_results_job_id'), 'screening_results', ['job_id'], unique=False)
    op.create_index(op.f('ix_screening_results_resume_id'), 'screening_results', ['resume_id'], unique=False)
    op.create_index(op.f('ix_screening_results_status'), 'screening_results', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screening_results_status'), table_name='screening_results')
    op.drop_index(op.f('ix_screening_results_resume_id'), table_name='screening_results')
    op.drop_index(op.f('ix_screening_results_job_id'), table_name='screening_results')
    op.drop_index(op.f('ix_screening_results_decision'), table_name='screening_results')
    op.drop_index(op.f('ix_screening_results_created_at'), table_name='screening_results')
    op.drop_table('screening_results')
    op.drop_index(op.f('ix_resumes_created_at'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_candidate_name'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_candidate_email'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_model_metadata_version'), table_name='model_metadata')
    op.drop_index(op.f('ix_model_metadata_is_active'), table_name='model_metadata')
    op.drop_table('model_metadata')
    op.drop_index(op.f('ix_jobs_title'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###

